baseURL: "https://cesarchavezp29.github.io/"
title: Carlos César Chávez Padilla
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Data
          url: data/
          weight: 4

params:
    description: "Carlos César Chávez Padilla - Development Economist | Research Professional at the University of Chicago, Center for Economics of Human Development | Research on development economics, political economy, and Latin America"
    author: Carlos César Chávez Padilla
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","projects","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Carlos César Chávez Padilla
          subtitle: "I am a Research Professional at the Center for Economics of Human Development at the University of Chicago, where I collaborate with Prof. James J. Heckman on early childhood skill formation. I am currently pursuing an MA in Public Policy at the Harris School of Public Policy and applying for Economics PhD programs for Fall 2026. My research focuses on development economics, political economy, and Latin America, particularly Peru."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:cesarchavezpadilla@gmail.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com
        - name: GitHub
          url: https://github.com/cesarchavezp29

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Carlos César Chávez Padilla"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2