r"""Build data/wordcloud.yaml from the abstracts of every paper. Counts content words (English + Spanish),
excluding connectors/stopwords and generic academic filler. Output feeds the word cloud on the Search page.
"""
import re
import glob
from pathlib import Path
from collections import Counter

ROOT = Path(r"D:\Investigacion\cesarchavezp29.github.io")

STOP = set("""
the a an and or but of to in on for with by from as at is are was were be been being this that these those
it its we our i my they their he she his her which who whom whose what when where how why not no nor so than
then also more most less very can could may might will would should do does did has have had using used use
between within across into over under about after before both each all any some such only even if because
while whether against through per via one two three our than into about up down out off above below
paper study find finds found results result show shows showed using used approach method methods data model
models effect effects evidence analysis estimate estimates examine examines test tests across set sets
el la los las un una unos unas de del y e o u que en con por para se su sus lo al es son este esta estos estas
como mas pero ni si entre sobre sin hacia desde cada todo toda todos todas tambien donde cuando ya muy son
mide segun cuyo cuya
""".split())


def abstract_of(md):
    t = open(md, encoding="utf-8").read()
    m = re.search(r"#####\s*Abstract\s*(.*?)(?:\n#####|\n---|\Z)", t, re.S)
    if not m:
        m = re.search(r"^summary:\s*\"?(.*?)\"?\s*$", t, re.M)
        return m.group(1) if m else ""
    return m.group(1)


words = Counter()
for md in glob.glob(str(ROOT / "content" / "papers" / "*" / "index.md")):
    txt = abstract_of(md).lower()
    for w in re.findall(r"[a-záéíóúñ][a-záéíóúñ\-]{2,}", txt):
        w = w.strip("-")
        if len(w) < 3 or w in STOP:
            continue
        words[w] += 1

top = [(w, c) for w, c in words.most_common(48) if c >= 2]
lines = ["# Auto-generated by gen_wordcloud.py — top content words across all abstracts."]
for w, c in top:
    lines.append(f"- word: \"{w}\"\n  count: {c}")
(ROOT / "data" / "wordcloud.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote data/wordcloud.yaml ({len(top)} words). Top 12:", top[:12])
